// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "67a0f2c2-2d4f-4cb2-9c04-3756f5770914");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575400120);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2015);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575400089);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6936ac02-a738-4ce2-86e4-110e825e296c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575400115074");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575401907074");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575400097037");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575403697037");
user_pref("browser.search.region", "AT");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575400092");
user_pref("browser.slowStartup.averageTime", 21449);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191031085722");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575400091);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575400092597");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "52ad2b85108249248db94f9e6de047b4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1b10bc02-7f76-436a-83ea-473167fc97e4\",\"screenshots@mozilla.org\":\"d93a7d90-62eb-484a-8c94-475febfcab26\",\"webcompat-reporter@mozilla.org\":\"bb47d913-8a1b-4fd4-b053-c6e46e6faa01\",\"webcompat@mozilla.org\":\"eac5d1da-26f0-495d-8a24-da117f388649\",\"default-theme@mozilla.org\":\"1b677d3e-19e2-47c6-bf87-12135c0b7bd1\",\"google@search.mozilla.org\":\"c383ecc4-1981-4757-b6a6-a90aa79327d9\",\"amazondotcom@search.mozilla.org\":\"238e39c0-5ed8-4ea7-9d38-b166b3ec29fd\",\"bing@search.mozilla.org\":\"5077e8d4-138b-4418-8209-72f1fc5212d9\",\"ddg@search.mozilla.org\":\"7a160e26-f761-48b4-ade0-38af7f2edf8a\",\"ebay@search.mozilla.org\":\"6d6e884f-863d-4585-9127-27de2f7a5e0a\",\"twitter@search.mozilla.org\":\"03c1f9cd-4836-4218-a26a-f58050befe80\",\"wikipedia@search.mozilla.org\":\"0283d6ec-f103-43b9-8799-f8d1538ffb31\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575400114);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191031085722");
user_pref("media.gmp-manager.lastCheck", 1575400113);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 10215);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "75da7253-0a11-459c-a4b0-2b259aeb1b1b");
user_pref("security.sandbox.plugin.tempDirSuffix", "e41be1f9-4f6e-4b99-ba68-246caa9d6cfc");
user_pref("services.blocklist.pinning.checked", 1575396511);
user_pref("services.settings.clock_skew_seconds", 3601);
user_pref("services.settings.last_etag", "\"1575394175343\"");
user_pref("services.settings.last_update_seconds", 1575396511);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1575396511);
user_pref("services.settings.main.cfr-fxa.last_check", 1575396511);
user_pref("services.settings.main.cfr.last_check", 1575396511);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1575396511);
user_pref("services.settings.main.hijack-blocklists.last_check", 1575396511);
user_pref("services.settings.main.language-dictionaries.last_check", 1575396511);
user_pref("services.settings.main.normandy-recipes.last_check", 1575396511);
user_pref("services.settings.main.public-suffix-list.last_check", 1575396511);
user_pref("services.settings.main.sites-classification.last_check", 1575396511);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1575396511);
user_pref("services.settings.main.whats-new-panel.last_check", 1575396511);
user_pref("services.settings.security.onecrl.checked", 1575396511);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575400088);
user_pref("toolkit.telemetry.cachedClientID", "4da7d370-cc68-4d39-88b1-30997fff6522");
user_pref("toolkit.telemetry.previousBuildID", "20191031085722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
