// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.startupRolloutPrefs.services.sync.engine.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "9bd6e262-3006-4a49-a2b3-13bb646f2f35");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575275893);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575275862);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2d7b14af-7552-41bb-a42f-26c728a18f45}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575275867714");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575279467714");
user_pref("browser.search.region", "DE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575275865");
user_pref("browser.slowStartup.averageTime", 1741);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191031085722");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575275864);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575275865502");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "929c1c7d77664d7794e9644556a8af78");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"678180cf-4313-4a6d-871f-89a31e03b2bd\",\"screenshots@mozilla.org\":\"09b41970-2b4e-4fac-85d4-bea1554a3485\",\"webcompat-reporter@mozilla.org\":\"95f1c575-aee0-4ce0-bc2c-2574fc5ba006\",\"webcompat@mozilla.org\":\"43ffba66-7d06-4528-962f-0446116c3ea6\",\"default-theme@mozilla.org\":\"d99b82d2-7b58-4d77-82c2-0135b282fe79\",\"google@search.mozilla.org\":\"da370a62-c4d6-4989-805b-cf849b8921e8\",\"amazondotcom@search.mozilla.org\":\"416c2c0f-7944-4678-a822-5385908093de\",\"bing@search.mozilla.org\":\"76ce6a79-b007-4ecc-9d8f-c5f6cd591bcd\",\"ddg@search.mozilla.org\":\"9a01aad6-281d-448c-a8ec-a2c264191d05\",\"ebay@search.mozilla.org\":\"0bd97d81-93df-498f-b979-ddd3810b2232\",\"twitter@search.mozilla.org\":\"ee13a5f5-9cf6-49a5-bc9c-12bedcfb522f\",\"wikipedia@search.mozilla.org\":\"c9bef671-2a85-49a2-a2b8-93046c386638\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575275885);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191031085722");
user_pref("media.gmp-manager.lastCheck", 1575275884);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "aedaaced-9fb0-474e-b822-4bd940c10f92");
user_pref("security.sandbox.plugin.tempDirSuffix", "560c33ab-6707-494b-9dca-fced4d8aba30");
user_pref("services.blocklist.pinning.checked", 1575275884);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1575158449963\"");
user_pref("services.settings.last_update_seconds", 1575275884);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1575275884);
user_pref("services.settings.main.cfr-fxa.last_check", 1575275884);
user_pref("services.settings.main.cfr.last_check", 1575275884);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1575275884);
user_pref("services.settings.main.hijack-blocklists.last_check", 1575275884);
user_pref("services.settings.main.language-dictionaries.last_check", 1575275884);
user_pref("services.settings.main.normandy-recipes.last_check", 1575275884);
user_pref("services.settings.main.public-suffix-list.last_check", 1575275884);
user_pref("services.settings.main.sites-classification.last_check", 1575275884);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1575275884);
user_pref("services.settings.main.whats-new-panel.last_check", 1575275884);
user_pref("services.settings.security.onecrl.checked", 1575275884);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "53ec9d3b-2e21-4151-a4c8-68ffec34870b");
user_pref("toolkit.telemetry.previousBuildID", "20191031085722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "holdback");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
