name: build-latest

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install goss and dgoss
      run: |
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o $HOME/goss
        chmod +rx $HOME/goss
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/dgoss -o $HOME/dgoss
        chmod +rx $HOME/dgoss
    - name: Build and test image
      run: ./build-latest.sh ${{ secrets.SAKULI_VERSION }} ${{ secrets.NPM_TOKEN }} ${{ secrets.NODE_VERSION }}
      env:
        PATH: $PATH:$HOME
        SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Publish image
      run: docker push taconsol/sakuli:latest

