name: build-release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '12'
    - name: Install goss and dgoss
      run: |
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o $HOME/goss
        chmod +rx $HOME/goss
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/dgoss -o $HOME/dgoss
        chmod +rx $HOME/dgoss
    - name: Set SAKULI_VERSION according to tag
      run: echo "SAKULI_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Add HOME directory to PATH
      run: echo "$HOME" >> $GITHUB_PATH
    - name: Build and test image
      run: |
        ./build-base.sh
        ./build-release.sh $SAKULI_VERSION ${{ secrets.NPM_TOKEN }}
      env:
        SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Publish image
      run: docker push taconsol/sakuli:${SAKULI_VERSION}
