name: build-release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '12'
    - name: Install goss and dgoss
      run: |
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o $HOME/goss
        chmod +rx $HOME/goss
        curl -L https://github.com/aelsabbahy/goss/releases/latest/download/dgoss -o $HOME/dgoss
        chmod +rx $HOME/dgoss
    - name: Set SAKULI_VERSION according to pushed tag
      run: echo "::set-env name=SAKULI_VERSION::${GITHUB_REF#refs/*/v}
    - name: Build and test image
      run: |
        export PATH=$PATH:$HOME
        ./build-release.sh $SAKULI_VERSION ${{ secrets.NPM_TOKEN }} ${{ secrets.NODE_VERSION }}
      env:
        SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Publish image
      run: docker push taconsol/sakuli:${SAKULI_VERSION}
